### ISSUE TITLE
Difficult/impossible to scroll down in modal window when creating page components

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov#529]
E.g. here when creating a media with text component, no scroll bar appears, so it's not possible to scroll down to the other options in this component.

I haven't been able to replicate this issue in the demo site, but it has come up in the SEND Local Offer, our two sites, and from Slack, Hammersmith and Fulham have run into the main issue.

I think this is pretty disruptive to content designers. I just hadn't reported this until now as I thought it was isolated to our instance.

![image](https://user-images.githubusercontent.com/19519457/232770986-03486aeb-b338-4d87-b432-f93df7665dc3.png)

**Comment by keelanfh** [comment]
@willguv one for the backlog group?

**Comment by andybroomfield** [comment]
Might be a Gin issue, we had a seperate one where the popup was jumping on page scroll. 
But you could try the following css and see if it fixes it (needs to be in a custom module)
````css
/* Fix layout paragraphs jumping by temp setting the popup to max height */
.ui-dialog.lpb-dialog .ui-widget-content.ui-dialog-content {
  max-height: calc(98vh - 55px - 75px) !important;
}
````
