### ISSUE TITLE
Adopt and tweak Drupal 11 "create menu"

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#620]
The double nesting on the Content menu makes it slow to pick the item you want

![Image](https://github.com/localgovdrupal/localgov/assets/708140/4dd8d356-3149-403a-a0ea-502a5fa54dd8)

Content editors do this a lot, so we should optimise this

Is it possible to remove "Add content >" from the content menu, bring everything up a level and reorganise it in a way that makes sense?

UPDATE @andybroomfield flagged an ongoing conversation on Drupal.org about this, and proposals for a "Create" menu

**Comment by willguv** [comment]
This is a bit more like it - ordering needs a bit more thought



![Image](https://github.com/localgovdrupal/localgov/assets/708140/e2784a60-1c08-4259-9c45-80e91edc62fd)

**Comment by davidupjohn** [comment]
Without the word 'Add content' how do I know what selecting one of those drop downs will go to ? Will it be a list of all step-by-step pages ? or will it take me to adding a new step-by-step page ? If you are using a screen reader where is the context of this menu ?

**Comment by willguv** [comment]
Hmmm... good point, thanks @davidupjohn. Some would be creating new content, others link to the lists of things eg alert banners

Can you think of any ways of reducing nesting, or am I trying to force this to do something it can't do? Cheers

**Comment by andybroomfield** [comment]
[Long thread on Drupal.org ](https://www.drupal.org/project/drupal/issues/2377543) about creating a `new` or `Create content` menu. 
There is also [New “content creation” menu proposal](https://www.drupal.org/project/ideas/issues/3203618)

This looks like the way to go, we could maybe add one with menu link group in the short term?

**Comment by willguv** [comment]
This is really useful - thanks Andy!

I've pulled a few things over from the Structure menu (eg add facet type) to address the same need

Can menu link groups be used to create new top level items in the nav?

**Comment by willguv** [comment]
Content group: like this idea

David: how about shortcut buttons for the items you create all the time?

**Comment by davidupjohn** [comment]
Yes we have shortcuts on our public site (not LGD) for event authors who log in rarely and just do one thing. I never use it personally and think there are other parts to focus effort into.  But I use it every day. Its you use it sparingly a shortcut might be good.

![image](https://github.com/localgovdrupal/localgov/assets/115223572/30cd8181-afea-4bce-acd5-48e17879e2ac)

**Comment by GC-92** [comment]
Hi there,

I actually kept the original 'Content' "dashboard" (I will call it that!) for myself and 'Administrator' roles on my site.

Then with custom roles and permission customisation, I created other options in the top toolbar which I tested with dummy user accounts.

Here are some screenshots:

Going in the 'views' and 'settings' of the view for allows you to customise the settings. It took a while to get my head around but it has been well received so far, and 'subtracting' every option during our new site launching is probably helpful to our teams.

I also added GOV.UK links and a 'mailto' link which creates an email to myself if they ever wanted to give feedback or request help, which has filled body/subject text for their issue.

![LGD Custom Menus with limited options for editors - Screenshot 2023-09-12 143351 2](https://github.com/localgovdrupal/localgov/assets/110611127/65dfca90-714e-4743-bb26-cfa5354ccb37)


![LGD Custom Menus with limited options for editors - Screenshot 2023-09-12 143351](https://github.com/localgovdrupal/localgov/assets/110611127/31094848-c68b-43b6-8dcc-ba8be024c8d3)

**Comment by andybroomfield** [comment]
See also [Tasty backend](https://drupal.org/project/tasty_backend) for an alternative implementation.

**Comment by willguv** [comment]
@willguv to propose a new menu for discussion. Any flexibility on icons/ styling

**Comment by andybroomfield** [comment]
Using menu link group.

<img width="1213" alt="Screenshot 2023-09-13 at 2 31 53 pm" src="https://github.com/localgovdrupal/localgov/assets/1467480/88402b82-464e-4c13-9fdf-945fd4c93a86">

**Comment by andybroomfield** [comment]
Config to install this in an existing site.
```yaml
langcode: en
status: true
dependencies: {  }
id: localgov_menu_link_group_new
group_label: New
weight: -99
parent_menu: admin
parent_menu_link: system.admin
child_menu_links:
  - 'localgov_menu_link_group:admin_toolbar_tools.extra_links:node.add:services'
  - 'localgov_menu_link_group:admin_toolbar_tools.extra_links:node.add:guide'
  - 'localgov_menu_link_group:admin_toolbar_tools.extra_links:node.add:directory'
  - 'localgov_menu_link_group:admin_toolbar_tools.extra_links:node.add:news'
  - 'localgov_menu_link_group:admin_toolbar_tools.extra_links:node.add:step_by_step'
  - 'admin_toolbar_tools.extra_links:node.add.localgov_event'
  - 'admin_toolbar_tools.extra_links:node.add.localgov_subsites_overview'
  - 'admin_toolbar_tools.extra_links:node.add.localgov_subsites_page'
  - 'admin_toolbar_tools.extra_links:add_media'
```
