### ISSUE TITLE
Make it easier to add images and documents

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov#705]

**Comment by dedavidson** [comment]
The fix for this is to add config to `modules/localgov_media/config/optional/linkit.linkit_profile.default.yml` the `localgov_core` project. ( https://github.com/localgovdrupal/localgov_core/blob/2.x/modules/localgov_media/config/optional/linkit.linkit_profile.default.yml )

 It requires adding the following config to the `matchers` section:
```
  <a uuid>:
    id: 'entity:media'
    uuid: <a uuid>
    settings:
      metadata: ''
      bundles:
        document: document
      group_by_bundle: false
      substitution_type: media
      limit: 100
    weight: 0
```
